export const countries = [
  "Việt Nam", "Afghanistan", "Ai Cập", "Albania", "Algérie", "Andorra", "Angola", 
  "Antigua và Barbuda", "Áo", "Ả Rập Xê Út", "Argentina", "Armenia", "Azerbaijan", 
  "Ba Lan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belize", 
  "Bénin", "Bhutan", "Bỉ", "Bồ Đào Nha", "Bolivia", "Bosna và Hercegovina", 
  "Botswana", "Brasil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", 
  "Campuchia", "Cameroon", "Canada", "Cabo Verde", "Chile", "Colombia", "Comoros", 
  "Cộng hòa Congo", "Cộng hòa Dân chủ Congo", "Cộng hòa Dominica", "Cộng hòa Séc", 
  "Cộng hòa Trung Phi", "Costa Rica", "Croatia", "Cuba", "Djibouti", "Dominica", 
  "Đan Mạch", "Đài Loan", "Đông Timor", "Đức", "Ecuador", "El Salvador", 
  "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Gabon", "Gambia", "Ghana", 
  "Grenada", "Gruzia", "Guatemala", "Guiné-Bissau", "Guiné Xích Đạo", "Guinea", 
  "Guyana", "Hà Lan", "Haiti", "Hàn Quốc", "Hoa Kỳ", "Honduras", "Hungary", 
  "Hy Lạp", "Iceland", "Ấn Độ", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", 
  "Jamaica", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", 
  "Kyrgyzstan", "Lào", "Latvia", "Lesotho", "Liban", "Liberia", "Libya", 
  "Liechtenstein", "Litva", "Luxembourg", "Madagascar", "Malawi", "Malaysia", 
  "Maldives", "Mali", "Malta", "Maroc", "Marshall", "Mauritania", "Mauritius", 
  "México", "Micronesia", "Moldova", "Monaco", "Mông Cổ", "Montenegro", 
  "Mozambique", "Myanmar", "Na Uy", "Namibia", "Nam Sudan", "Nauru", "Nepal", 
  "New Zealand", "Nga", "Nhật Bản", "Nicaragua", "Niger", "Nigeria", "Oman", 
  "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", 
  "Peru", "Pháp", "Phần Lan", "Philippines", "Qatar", "Romania", "Rwanda", 
  "Saint Kitts và Nevis", "Saint Lucia", "Saint Vincent và Grenadines", "Samoa", 
  "San Marino", "São Tomé và Príncipe", "Sénégal", "Serbia", "Seychelles", 
  "Sierra Leone", "Singapore", "Síp", "Slovakia", "Slovenia", "Somalia", 
  "Sri Lanka", "Sudan", "Suriname", "Syria", "Tajikistan", "Tanzania", 
  "Tây Ban Nha", "Tchad", "Thái Lan", "Thổ Nhĩ Kỳ", "Thụy Điển", "Thụy Sĩ", "Togo", 
  "Tonga", "Triều Tiên", "Trinidad và Tobago", "Trung Quốc", "Tunisia", 
  "Turkmenistan", "Tuvalu", "Úc", "Uganda", "Ukraina", "Uruguay", "Uzbekistan", 
  "Vanuatu", "Vatican", "Venezuela", "Ý", "Yemen", "Zambia", "Zimbabwe",
].sort((a, b) =>
  a === "Việt Nam" ? -1 : b === "Việt Nam" ? 1 : a.localeCompare(b)
);
